version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: FinancasApp/Dockerfile
    ports:
      - "5145:80" 
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" 

  webapi2:
    build:
      context: .
      dockerfile: FinancasApp/Dockerfile
    ports:
      - "7145:80" 
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" 

  webapi3:
    build:
      context: .
      dockerfile: FinancasApp/Dockerfile
    ports:
      - "4145:80" 
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" 

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro